apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.deployment.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
